apiVersion: apps/v1
kind: Deployment
metadata:
  name: brownrook-idc
  namespace: brownrook-idc
  labels:
    app: brownrook-idc
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: brownrook-idc
  template:
    metadata:
      labels:
        app: brownrook-idc
    spec:
      terminationGracePeriodSeconds: 45    
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        runAsNonRoot: true
      containers:
        - name: brownrook-idc
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          image: ghcr.io/larocquemb/brownrook-idc:59cdb82c29206e6c1199c131b516e7505b0aad81
          imagePullPolicy: Always
          env:
            - name: APP_VERSION
              value: "0.1.0"
            - name: GIT_COMMIT
              value: "unknown"
            - name: BUILD_NUMBER
              value: "00"
            - name: IMAGE_REF
              value: "ghcr.io/larocquemb/brownrook-idc:unknown"  
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: brownrook-idc-config
            - secretRef:
                name: brownrook-idc-secret
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

