apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - argocd-cm.yaml  
  - argocd-cmd-params-cm.yaml  
  - repo-brownrook-infra.yaml
  - ingress.yaml
  - certificate.yaml

