apiVersion: v1
kind: Secret
metadata:
  name: repo-brownrook-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/larocquemb/brownrook-infra.git
  type: git
