apiVersion: v1
kind: Secret
metadata:
  name: brownrook-idc-env
  namespace: idc
type: Opaque
stringData:
  OIDC_ISSUER: "https://login.microsoftonline.com/<TENANT_ID>/v2.0"
  OIDC_JWKS_URL: "https://login.microsoftonline.com/<TENANT_ID>/discovery/v2.0/keys"
  OIDC_AUDIENCE: "<CLIENT_ID>"
  OIDC_SCOPE: "access_as_user"
  