apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledger
  namespace: argocd
spec:
  project: brownrook
  source:
    repoURL: https://github.com/larocquemb/home-budget-pipeline.git
    targetRevision: KAN-68
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: home-budget
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
