apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  nodeSelector:
    kubernetes.io/hostname: arsene
  containers:
    - name: cuda-test
      image: nvidia/cuda:13.0.2-base-ubi9
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
